###########################
# Project Configuration
###########################
# Project Name:        Lotus-Retreat
# Author:              Dobreanu Stefan
# Description:         
###########################

services:
  app:
    image: webdevops/php-nginx:8.3
    platform: linux/amd64
    container_name: dev_lotus_retreat_app
    working_dir: /app
    volumes:
      - ./:/app
      - ./public:/app/public
    environment:
      - PHP_DISPLAY_ERRORS=On
      - PHP_MEMORY_LIMIT=128M
      - PHP_UPLOAD_MAX_FILESIZE=50M
      - PHP_POST_MAX_SIZE=50M
      - PHP_MAX_EXECUTION_TIME=30
      - PHP_MAX_INPUT_TIME=60
      - WEB_DOCUMENT_ROOT=/app/public
      - APP_ENV=stage
      - APP_DEBUG=true
      - APP_NAME=Lotus-Retreat
      - APP_KEY=base64:+1N1xTSxhanLlAenE0xEm/JkYIxFpN5xINVFNHPKmr8=
      - DB_CONNECTION=mysql
      - DB_HOST=192.168.1.133
      - DB_PORT=3306
      - DB_DATABASE=dev_lotusretreat_ro
      - DB_USERNAME=root
      - DB_PASSWORD=Hypeneboss2024@-
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - REDIS_CLIENT=predis
    restart: always
    ports:
      - "8834:80"
    depends_on:
      - redis
    networks:
      - lotus_network

  redis:
    image: redis:alpine
    container_name: dev_lotus_retreat_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - lotus_network
    command: redis-server --appendonly yes

networks:
  lotus_network:
    driver: bridge

volumes:
  redis_data:
    driver: local

